name: Publish Package to npmjs

on:
  workflow_dispatch:
  push:
    branches:
      - release

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get-release-version.outputs.version }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wemogy/get-release-version-action@v4.3.2
        id: get-release-version
        with:
          git-username: ntrannghia
          git-email: ntrannghia@gmail.com
          mode: 'semantic'

  build:
    needs: [tag]
    name: Build & Test
    uses: ./.github/workflows/workflow-build.yaml
    permissions:
      contents: read
      pull-requests: write
    with:
      version: ${{ needs.tag.outputs.version }}
      upload: true
    secrets: inherit

  release:
    needs: [tag, build]
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist from Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-re-export
          path: dist
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Set package version
        run: |
          # Automatically increment the patch version
          # Change 'patch' to 'minor' or 'major' to increment those version numbers instead
          # patch: 0.0.3 → 0.0.4 (increments the last number)
          # minor: 0.0.3 → 0.1.0 (increments the middle number, resets last to 0)
          # major: 0.0.3 → 1.0.0 (increments the first number, resets others to 0)
          npm version patch --no-git-tag-version
          
          # Get the new version for logging
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "Auto-incremented version to: $NEW_VERSION"

      - name: Publish to npm
        env:
          HUSKY: 0 # Disable Husky hooks
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --provenance --access public       
